---
version: "0.6.1"

services:
  diary-portal:
    image: ghcr.io/gallexy/diary-portal:latest
    container_name: diary-portal
    volumes:
      - $PWD/config/:/app/config/
    tty: true
    network_mode: host
    restart: unless-stopped